stages:
  data_ingestion:
    cmd: python src/animalDetection/pipeline/stage_01_data_ingestion.py
    deps:
      - src/animalDetection/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/animal_detection_dataset

  prepare_base_model:
    cmd: python src/animalDetection/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/animalDetection/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - IMAGE_SIZE
      - LEARNING_RATE
      - DROPOUT_RATE
      - INCLUDE_TOP
      - WEIGHTS
      - CLASSES
    outs:
      - artifacts/prepare_base_model

  training:
    cmd: python src/animalDetection/pipeline/stage_03_training.py
    deps:
      - src/animalDetection/pipeline/stage_03_training.py
      - src/animalDetection/components/prepare_callbacks.py
      - config/config.yaml
      - artifacts/data_ingestion/animal_detection_dataset
      - artifacts/prepare_base_model
    params:
      - EPOCHS
      - BATCH_SIZE
      - AUGMENTATION
      - IMAGE_SIZE
    outs:
      - artifacts/training/model.h5


  evaluation:
    cmd: python src/animalDetection/pipeline/stage_04_evaluation.py
    deps:
      - src/animalDetection/pipeline/stage_04_evaluation.py
      - config/config.yaml
      - artifacts/data_ingestion/animal_detection_dataset
      - artifacts/training/model.h5
    params:
      - IMAGE_SIZE
      - BATCH_SIZE
    metrics:
    - scores.json:
        cache: false